{% set name = "jupyter" %}
{% set version = "1.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: jupyter-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: d9dc4b3318f310e34c82951ea5d6683f67bed7def4b259fafbfe4f1beb1d8e5f

build:
  number: 9 # trigger

requirements:
  host:
    - python
    - pip
    - setuptools
    - wheel
  run:
    - python
    - ipykernel
    - ipywidgets # [not s390x]
    - jupyter_console
    # Add jupyterlab to meta package, see https://github.com/jupyter/jupyter/pull/615
    - jupyterlab # [not s390x]
    - nbconvert
    - notebook # [not s390x]
    - qtconsole   # [not s390x]

test:
  requires:
    - pip
  commands:
    - pip check || true    # [s390x]
    - pip check # [not s390x]
    - jupyter --help
    - jupyter console -h
    - jupyter lab -h # [not s390x]
    - jupyter notebook -h # [not s390x]

about:
  home: https://jupyter.org
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Jupyter metapackage. Install all the Jupyter components in one go.
  description: |
    Jupyter Notebook is a web application, a browser-based tool for interactive authoring of documents
    which combine explanatory text, mathematics, computations and their rich media output.
  doc_url: https://docs.jupyter.org
  dev_url: https://github.com/jupyter/jupyter

extra:
  recipe-maintainers:
    - minrk
    - ocefpaf
