{% set version = "1.0.0" %}

package:
  name: jupyter
  version: {{ version }}

build:
  number: 7
  noarch: python

requirements:
  host:
    - python
    - pip
  run:
    - python
    - notebook
    - qtconsole   # [not ppc64le]
    - jupyter_console
    - nbconvert
    - ipykernel
    - ipywidgets

test:
  commands:
    - jupyter --help
    - jupyter nbextension list

about:
  home: http://jupyter.org
  license: BSD 3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'Jupyter metapackage. Install all the Jupyter components in one go.'
  description: |
    Jupyter Notebook is a web application, a browser-based tool for interactive authoring of documents
    which combine explanatory text, mathematics, computations and their rich media output.
  doc_url: http://jupyter.readthedocs.org/
  doc_source_url: https://github.com/jupyter/notebook/blob/master/docs/source/index.rst
  dev_url: https://github.com/jupyter/jupyter

extra:
  recipe-maintainers:
    - minrk
    - ocefpaf
    - xylar
