travis:
  secure:
    BINSTAR_TOKEN: sjbriS5yQrJPRhy39PFPc+QbQn3iMmscolXqLbpnI3YH2aR8ndEJt+b+YkaiJenP4+r3ZYAH/5usJe7ZhXugyRhJvBcPtEJql0KVfi5shUGpbDGEK+RUIRPd3K/JuTkmoHB5LzWwn0jiR3Ii3KTC5NChqM6J64SIelI0JZdUH8AJnP+dbPzY0W8TjgES4HHTO3MZviHAoQuAr/ANE8CUC0E8I7I/IDsON9+Zq9sO9F29EfneWDtblxpV5IsW6/KOP9l2FDGZLUqI1F4iz5+jrWMRr1VJlY7c90V9ts2LOyvC2ip230NG9yIrfGMUfxuq9IpdOKfFI6K5vpXxQxPj+cqRRK6DXKLHcp5NBz7tVbBcUqf5G2iWkiWnEnyIVpMjN/kWYn0SQjnS+rvX/uO0X8q1jrMe10/x4ZhPcUfAqgWnauXSgHw1+A8zqqtEo7KKSGcl6WfvWLPukaJmK9dvh3w/MCUpHMhUGT0vY/ZJUT4O6QhhLffdB7+xtdFHZxKVbxrYQ/jqd1x+K75/LH5xXq/rW8ugo9d3cEXKdiXY/CG4UhYqnYJciyoZbWsrbOeivEUfaYFjy2RN9SXB0js0NZBg9h06p/JYRxGYpyzIi/w9oL8e78EmC/xgyR49HUuhR3NwuUnjAMNdVVskNLMZ3r21vGFwjd+BemXeEkOJD58=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
