travis:
  secure:
    BINSTAR_TOKEN: N9Xf9IIu4Jmi7d59tyHB7b3ihRRj/mFM4pNNRBIdvcMBEjuWqvHWtlbie4aqTyIwXfttWLyR65kc6s01sHHGFkjLsWcoc2ikfTHP2SpE+XhqcRHm/l5R2shPZ7dICS37i0jo+MhRebkGR1H3iOfvykt32xpv/FkTl8JWS92vuY2JdbfENEN1OQwDTq5ZJIHH8qf/c4gS7LMggK7l1g2OrBwuUrDyBbxNyMNTX/nvjO+jXkECWPSWmEXNSqwt0hZG7CQk8kmmR/pSf5wItZ+jGxgiRDfldrhkCZuKwU48OjmFZgOkPfoukhtUNXu2xXrJHX5ot+iKC9ZPIK+dIWkIbBm+kaos6N3fpEJwrULMr9E4ywpx7VIx0+RYsl4hMO0U1YIrx2qko5jG6yckIP1dOX47Y82n7bMs626f3N3lXQZ+nWiVCIOILUxmzPxK2GVMs7wPd/iXXZhr/n+h3eORBcOogbIH2hPfm3RM3G0ye9fMiBrl7b8zR11lLL02h8CtF/5bnZk4CLkdFwYq7oH9f+NP66nfS9FO5ahiZ8gMPSb+wjbTDLMWszBF3tiTLnCtLT0N33uLAADf7RZ2hX5hrBrG7PTHroIhrNhxL8mTIQHYFgV5Sf+RvJXuUqewaFCPRP6HV8HSqzuWoWI9s2slvSFVte315x6jVmcGc3a6bxA=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
